"""
LLM Analyst — uses Claude to review each ORB signal before entry.

For every candidate signal the analyst receives:
  - symbol + ORB rationale (price vs OR levels, VWAP, RS)
  - clean market snapshot (price, spread, volume, ATR)

It returns:
  action     : ENTER_LONG | ENTER_SHORT | SKIP | PASS (error fallback)
  confidence : 0.0–1.0
  reasoning  : one-sentence explanation

Results are cached per (symbol, UTC-minute) — only one API call per
symbol per minute even if _scan_and_enter fires every 5 seconds.

Set ANTHROPIC_API_KEY environment variable before running:
  export ANTHROPIC_API_KEY=sk-ant-...
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


@dataclass
class LLMAnalysis:
    action: str        # ENTER_LONG | ENTER_SHORT | SKIP | PASS
    confidence: float  # 0.0–1.0
    reasoning: str
    ts: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


_SYSTEM = (
    "You are a professional quantitative day trader specialising in Opening Range Breakout "
    "(ORB) momentum strategies on US equities. Your job is to act as a second-opinion filter "
    "on signals already generated by a rule-based system. "
    "Respond ONLY with a single JSON object — no markdown fences, no extra text."
)


class LLMAnalyst:
    """
    Claude-powered signal confirmation filter.

    Usage
    -----
    analyst = LLMAnalyst(model="claude-opus-4-6")
    analysis = analyst.analyze(symbol, snapshot, rationale)
    if analysis.action == "SKIP":
        ...  # LLM vetoed the trade
    """

    def __init__(self, model: str = "claude-opus-4-6"):
        api_key = os.getenv("ANTHROPIC_API_KEY")
        if not api_key:
            raise ValueError(
                "ANTHROPIC_API_KEY environment variable is not set.\n"
                "Fix: export ANTHROPIC_API_KEY=sk-ant-..."
            )
        try:
            import anthropic
            self._client = anthropic.Anthropic(api_key=api_key)
        except ImportError:
            raise ImportError(
                "anthropic package not installed. Fix: pip install anthropic"
            )
        self._model = model
        self._cache: dict[str, LLMAnalysis] = {}
        logger.info("LLM analyst ready (model=%s)", model)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def analyze(
        self,
        symbol: str,
        snapshot: dict,
        signal_rationale: str,
    ) -> LLMAnalysis:
        """
        Ask Claude whether to confirm, alter, or veto a trade signal.
        Cached per (symbol, UTC-minute) to avoid redundant API calls.
        """
        cache_key = f"{symbol}:{datetime.now(timezone.utc).strftime('%Y%m%d%H%M')}"
        if cache_key in self._cache:
            cached = self._cache[cache_key]
            logger.debug("LLM cache hit for %s: %s", symbol, cached.action)
            return cached

        try:
            result = self._call_api(symbol, snapshot, signal_rationale)
        except Exception as exc:
            logger.warning(
                "LLM API error for %s (%s) — using PASS fallback", symbol, exc
            )
            result = LLMAnalysis(
                action="PASS",
                confidence=0.5,
                reasoning=f"api_error: {type(exc).__name__}",
            )

        self._cache[cache_key] = result
        logger.info(
            "LLM [%s] → %s  conf=%.2f  reason=%s",
            symbol, result.action, result.confidence, result.reasoning[:100],
        )
        return result

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _call_api(
        self, symbol: str, snapshot: dict, rationale: str
    ) -> LLMAnalysis:
        prompt = self._build_prompt(symbol, snapshot, rationale)
        msg = self._client.messages.create(
            model=self._model,
            max_tokens=256,
            system=_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        text = msg.content[0].text.strip()
        return self._parse(text, symbol)

    def _build_prompt(self, symbol: str, snapshot: dict, rationale: str) -> str:
        # Only send the fields Claude needs — keeps tokens low and costs down
        relevant = {
            k: v for k, v in snapshot.items()
            if k in (
                "last_price", "vwap", "or_high", "or_low",
                "atr", "spread_bps", "current_bar_volume", "avg_bar_volume",
            )
        }
        return (
            f"Symbol: {symbol}\n"
            f"ORB signal rationale: {rationale}\n"
            f"Market data: {json.dumps(relevant, default=str)}\n\n"
            "Rules you must follow:\n"
            "- LONG signals: price > OR high, price > VWAP, RS vs SPY positive\n"
            "- SHORT signals: price < OR low, price < VWAP, RS vs SPY negative\n"
            "- Reject if spread_bps > 25 or volume looks thin\n"
            "- Reject if ATR is unusually large (>3% of price) indicating chaotic action\n"
            "- Approve only clean, textbook breakouts\n\n"
            "Respond with a single JSON object:\n"
            '{"action": "ENTER_LONG" | "ENTER_SHORT" | "SKIP", '
            '"confidence": 0.0-1.0, "reasoning": "one sentence max"}'
        )

    def _parse(self, text: str, symbol: str) -> LLMAnalysis:
        try:
            start = text.find("{")
            end = text.rfind("}") + 1
            if start == -1 or end == 0:
                raise ValueError("no JSON object found")
            data = json.loads(text[start:end])
            action = str(data.get("action", "SKIP")).upper()
            if action not in ("ENTER_LONG", "ENTER_SHORT", "SKIP"):
                action = "SKIP"
            return LLMAnalysis(
                action=action,
                confidence=max(0.0, min(1.0, float(data.get("confidence", 0.5)))),
                reasoning=str(data.get("reasoning", ""))[:200],
            )
        except Exception as exc:
            logger.warning(
                "LLM parse error for %s: %s | raw=%r", symbol, exc, text[:300]
            )
            return LLMAnalysis(
                action="SKIP", confidence=0.0, reasoning="parse_error"
            )
